### PR TITLE
Add possibility to export events as iCal

### PR DESCRIPTION
**Pull request by GenieTim**
This PR adds the possibility to export events from the share screen as an .ical-file to import them into a calendar application.
It additionally links the events in the "mine"-table to the share view for simplified testing/sharing for organizers.

Possible issues to discuss:

- duration = parts * 45 min or longer in order to incorporate pauses?
- add more meta-info to the calendar event, e.g. the organizer?
- the design (i.e. choose a better icon, replace with text, ...)

### CODE REVIEW

**Comment by famoser** [comment]
Thanks, really useful!

I am sorry about fontawesome breaking the build due to the licensing issues. Its advantages (small build size, abundance of icons) currently outweight this nuisance. 

To the design questions:
- I'd skip modelling the pauses, as its up to the speaker how to structure the time.
- I would include the organizer, as its also shown on the webpage. 
- `fa-calendar-check` looks good to me as an icon

I'll test & publish the update in the evening.

**Comment by GenieTim** [comment]
Awesome, thanks. I just realized that with the library I am using, adding the organizer will only be possible if the php requirement is bumped up to >= 7.4|8.0 (see [here](https://github.com/markuspoerschke/iCal#version--upgrade)). I can either 

a) do that, bump the PHP version & use a newer version of the library,
b) switch library,
c) dump the library and do it manually,
d) just skip outputting organizer for now

What would be most suitable for your setups/& philosophy?

**Comment by famoser** [comment]
I did a quick refactor for consistency, and fully tested the implementation.

For your references, the changes I have made:
- Moved the iCal action & translation inside the `EventController`
- Linked the registered events also to the shared view (below the "own" events in the my events view)
- Loaded the required FontAwesome icon in the JavaScript

I did not include the organizer in the `iCal`:
- It requires the E-Mail of the organizer; which would need the explicit approval of the speaker to publish
- Just publishing `info@thealternative.ch` arguably does not make much sense. 
- The `Organizer` feature is not yet published in the dependency

Don't get fooled by the number of commits; I have not changed much with your contribution. It was well done. :) Also, nice usage of the `a` `title` attribute; I use this not often enough.

I will quickly draft a release and publish the changes.

**Comment by famoser** [comment]
Ah, concerning the `php` version: To bump to php 7.4 makes total sense; php 7.2 is already EOL. I generally do not have a strong opinion which php version to aim for.

**Pull request merged**
